
package electronichomes.UI.paneles;

import electronichomes.entidades.Empleado;
import electronichomes.entidades.Establecimiento;
import electronichomes.entidades.util.Rol;
import java.util.ArrayList;

/**
 *
 * @author CIROSS
 */
public class PanelDatosEmpleado extends javax.swing.JPanel {

    private ArrayList<Establecimiento> listaEstablecimientos;
    private Empleado empleado;
    private Rol[] listaRoles;
    
    /**
     * Creates new form PanelDatosEmpleado
     */
    public PanelDatosEmpleado() {
        initComponents();
        listaEstablecimientos = new Establecimiento().generarListaEstablemientos();
        listaRoles = Rol.values();
        inicializarCombos();
    }

    public PanelDatosEmpleado(String tituloPanel, String usuario, String contrasena, String cui, String nombre, String apellido, double salario, Rol rol, Establecimiento establecimiento) {
        this();
        this.jLabelTituloPanel.setText(tituloPanel);
        this.jTextFieldUsuario.setText(usuario);
        this.jTextFieldContrasena.setText(contrasena);
        this.jTextFieldCui.setText(cui);
        this.jTextFieldNombre.setText(nombre);
        this.jTextFieldApellido.setText(apellido);
        this.jTextFieldSalario.setText(Double.toString(salario));
        int indexRol = getIndexRol(rol);
        this.jComboBoxRol.setSelectedIndex(indexRol);
        int indexEstablecimiento = getIndexEstablecimiento(establecimiento);
        this.jComboBoxEstablecimientos.setSelectedIndex(indexEstablecimiento);
    }
    
    public void inicializarCombos() {
        this.jComboBoxEstablecimientos.addItem("");
        for (int i = 0; i < listaEstablecimientos.size(); i++) {
            this.jComboBoxEstablecimientos.addItem(listaEstablecimientos.get(i).getNombre());
        }
        
        for (int i = 0; i < listaRoles.length; i++) {
            this.jComboBoxRol.addItem(listaRoles[i].name());
        }
    }

    public Empleado getNuevoEmpleado() {
        try {
            String usuario = this.jTextFieldUsuario.getText();
            String contrasena = this.jTextFieldContrasena.getText();
            String cui = this.jTextFieldCui.getText();
            String nombre = this.jTextFieldNombre.getText();
            String apellido = this.jTextFieldApellido.getText();
            double salario = Double.parseDouble(jTextFieldSalario.getText());
            Rol rol = listaRoles[jComboBoxRol.getSelectedIndex()];
            int indexEst = jComboBoxEstablecimientos.getSelectedIndex()-1;
            Establecimiento establecimiento = listaEstablecimientos.get(indexEst);
        
            return new Empleado(usuario, contrasena, cui, rol, establecimiento, nombre, apellido, salario);
        } catch (Exception e) {
            System.out.println("Ocurrió un error al crear el usuario: " + e.getMessage());
            return null;
        }
        
    }
    
    private int getIndexRol(Rol rol) {
        for (int i = 0; i < this.listaRoles.length; i++) {
            if (listaRoles[i].name().equals(rol.name())) {
                return i;
            }
        }
        return 0;
    }
    
    private int getIndexEstablecimiento(Establecimiento establecimiento) {
        for (int i = 0; i < listaEstablecimientos.size(); i++) {
            if (listaEstablecimientos.get(i).equals(establecimiento)) {
                return i-1;
            }
        }
        return 0;
    }
    
    public void limpiarCampos() {
        this.jLabelTituloPanel.setText("Ingresar Empleado:");
        this.jTextFieldUsuario.setText("");
        this.jTextFieldContrasena.setText("");
        this.jTextFieldCui.setText("");
        this.jTextFieldNombre.setText("");
        this.jTextFieldApellido.setText("");
        this.jTextFieldSalario.setText("");
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloPanel = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldContrasena = new javax.swing.JTextField();
        jLabelContrasena = new javax.swing.JLabel();
        jLabelCui = new javax.swing.JLabel();
        jTextFieldCui = new javax.swing.JTextField();
        jLabelRol = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelSalario = new javax.swing.JLabel();
        jTextFieldSalario = new javax.swing.JTextField();
        jLabelEstablecimiento = new javax.swing.JLabel();
        jComboBoxRol = new javax.swing.JComboBox<>();
        jComboBoxEstablecimientos = new javax.swing.JComboBox<>();

        jLabelTituloPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTituloPanel.setText("Ingresar Empleado");

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUsuario.setText("Usuario:");

        jTextFieldUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextFieldContrasena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelContrasena.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelContrasena.setText("Contraseña:");

        jLabelCui.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCui.setText("CUI:");

        jTextFieldCui.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelRol.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelRol.setText("Rol:");

        jTextFieldNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jLabelApellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelApellido.setText("Apellido:");

        jTextFieldApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelSalario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSalario.setText("Salario:");

        jTextFieldSalario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelEstablecimiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEstablecimiento.setText("Establecimiento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelApellido)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUsuario)
                                    .addComponent(jLabelNombre)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelContrasena, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelCui)))
                                .addComponent(jLabelSalario)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldSalario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(jTextFieldApellido)
                            .addComponent(jTextFieldContrasena)
                            .addComponent(jTextFieldUsuario)
                            .addComponent(jTextFieldCui, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNombre)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelRol)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelEstablecimiento)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxEstablecimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelTituloPanel)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelContrasena))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCui)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSalario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstablecimiento)
                    .addComponent(jComboBoxEstablecimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRol)
                    .addComponent(jComboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxEstablecimientos;
    private javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelContrasena;
    private javax.swing.JLabel jLabelCui;
    private javax.swing.JLabel jLabelEstablecimiento;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelTituloPanel;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JTextField jTextFieldApellido;
    public javax.swing.JTextField jTextFieldContrasena;
    private javax.swing.JTextField jTextFieldCui;
    public javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldSalario;
    public javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
