
package electronichomes.UI.paneles;

import electronichomes.entidades.Empleado;
import electronichomes.entidades.Establecimiento;
import electronichomes.entidades.Existencia;
import electronichomes.entidades.Producto;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author CIROSS
 */
public class PanelSolicitudProducto extends javax.swing.JPanel {

    private ArrayList<Establecimiento> listaEstablecimientos;
    private Empleado empleado;
    
    /**
     * Creates new form PanelSolicitudProducto
     */
    public PanelSolicitudProducto() {
        initComponents();
        this.listaEstablecimientos = new Establecimiento().generarListaEstablemientos();
        inicializarComboBox();
    }
    
    public PanelSolicitudProducto(Empleado empleado) {
        this();
        this.empleado = empleado;
    }
    
    public void inicializarComboBox() {
        for (int i = 0; i < listaEstablecimientos.size(); i++) {
            this.jComboBoxEstablecimientos.addItem(listaEstablecimientos.get(i).getNombre());
        }
    }
    
    public Existencia getExistenciaSolicitada() {
        try {
            String codigoProducto = jTextFieldCodigo.getText();
            Producto producto = Producto.getProductoPorCodigo(codigoProducto);
            int cantidad = Integer.parseInt(jTextFieldCantidad.getText());
            int index = jComboBoxEstablecimientos.getSelectedIndex();
            Establecimiento establecimiento = this.listaEstablecimientos.get(index);
            
            return new Existencia(producto, establecimiento, cantidad);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error: " + e.getMessage());
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloPanel = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelCantidad = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabelMarca = new javax.swing.JLabel();
        jComboBoxEstablecimientos = new javax.swing.JComboBox<>();

        jLabelTituloPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTituloPanel.setText("Realizar Solicitud");

        jLabelCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCodigo.setText("Código de Producto:");

        jTextFieldCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelCantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCantidad.setText("Cantidad:");

        jTextFieldCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelMarca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMarca.setText("Establecimiento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCodigo)
                            .addComponent(jLabelCantidad)
                            .addComponent(jLabelMarca))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(jTextFieldCantidad)
                            .addComponent(jComboBoxEstablecimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelTituloPanel)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCodigo)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCantidad))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelMarca)
                        .addComponent(jComboBoxEstablecimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxEstablecimientos;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelTituloPanel;
    public javax.swing.JTextField jTextFieldCantidad;
    public javax.swing.JTextField jTextFieldCodigo;
    // End of variables declaration//GEN-END:variables
}
