
package electronichomes.UI;

import electronichomes.UI.paneles.PanelDatosProducto;
import electronichomes.entidades.Empleado;
import electronichomes.entidades.Establecimiento;
import electronichomes.entidades.Existencia;
import electronichomes.entidades.Producto;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CIROSS
 */
public class Bodega extends javax.swing.JFrame {

    private Empleado empleadoBodega;
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    /**
     * Creates new form Bodega
     */
    public Bodega() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Electronic-Homes");
        ImageIcon icono = new ImageIcon(getClass().getResource("/electronichomes/UI/images/icon.png"));
        setIconImage(icono.getImage());
        inicializarTabla();
    }
    
    public Bodega(Empleado empleadoBodega) {
        this();
        this.empleadoBodega = empleadoBodega;
        String nombreUsuario = empleadoBodega.getNombre() + " " + empleadoBodega.getApellido();
        this.jTextFieldUsuario.setText(nombreUsuario);
        jTextFieldRol.setText(empleadoBodega.getRol().name());
    }
    
    public void inicializarTabla() {
        
        modeloTabla.addColumn("Codigo Producto");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Marca");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Cantidad");
        modeloTabla.addColumn("Descripcion");

        this.jTable1.setModel(modeloTabla);
    }

    public void llenarTabla() {
        Existencia existencias = new Existencia();
        existencias.mostrarRegistros(modeloTabla, empleadoBodega);
    }
    
    public void actualizarTabla() {
        int filas = modeloTabla.getRowCount();
        for (int i = 0; i < filas; i++) {
            modeloTabla.removeRow(0);
        }
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonVerProductos = new javax.swing.JButton();
        jButtonEditarProducto = new javax.swing.JButton();
        jButtonIngresarNuevo = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelRol = new javax.swing.JLabel();
        jTextFieldRol = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(60, 90, 120));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setText("Productos en Bodega:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo de Producto", "Nombre", "Marca", "Precio", "Cantidad", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonVerProductos.setText("Ver Productos");
        jButtonVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerProductosActionPerformed(evt);
            }
        });

        jButtonEditarProducto.setText("Editar Producto");
        jButtonEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarProductoActionPerformed(evt);
            }
        });

        jButtonIngresarNuevo.setText("Ingresar Nuevo Producto");
        jButtonIngresarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarNuevoActionPerformed(evt);
            }
        });

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUsuario.setText("USUARIO:");

        jTextFieldUsuario.setEditable(false);
        jTextFieldUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelRol.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelRol.setText("ROL:");

        jTextFieldRol.setEditable(false);
        jTextFieldRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonVerProductos)
                            .addGap(58, 58, 58)
                            .addComponent(jButtonEditarProducto)
                            .addGap(58, 58, 58)
                            .addComponent(jButtonIngresarNuevo))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldUsuario))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelRol)
                                .addGap(41, 41, 41)
                                .addComponent(jTextFieldRol))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuario)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRol)
                    .addComponent(jTextFieldRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVerProductos)
                    .addComponent(jButtonEditarProducto)
                    .addComponent(jButtonIngresarNuevo))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerProductosActionPerformed
        llenarTabla();
    }//GEN-LAST:event_jButtonVerProductosActionPerformed

    private void jButtonEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarProductoActionPerformed
        String codigo = JOptionPane.showInputDialog("Ingrese el codigo del producto:");
        
        if (!codigo.equals("")) {
            Producto producto = Producto.getProductoPorCodigo(codigo);
            if (producto==null) {
                JOptionPane.showMessageDialog(null, "El codigo ingresado es incorrecto","Codigo incorrecto",JOptionPane.ERROR_MESSAGE);
            } else {
                String txtPrecio = String.valueOf(producto.getPrecio());
                PanelDatosProducto panel = new PanelDatosProducto("Editar Producto", producto.getCodigo(), producto.getNombre(), producto.getMarca(), txtPrecio, producto.getDescripcion());
                int boton = JOptionPane.showOptionDialog(null, panel, "Editar producto", 2, JOptionPane.PLAIN_MESSAGE, null, new String[]{"Guardar","Cancelar"}, null);
                
                if (boton==0) {
                    producto = panel.getNuevoProducto();
                    producto.ejecutarInstruccionPSQL(Producto.UPDATE);
                    this.actualizarTabla();
                }
            }
        
        }
        
    }//GEN-LAST:event_jButtonEditarProductoActionPerformed

    private void jButtonIngresarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarNuevoActionPerformed
        
        PanelDatosProducto panel = new PanelDatosProducto();
        panel.limpiarCampos();
        int boton = JOptionPane.showOptionDialog(null, panel, "Ingresar producto", 2, JOptionPane.PLAIN_MESSAGE, null, new String[]{"Guardar","Cancelar"}, null);

        if (boton==0) {
            Producto nuevoProducto = panel.getNuevoProducto();
            
            if (nuevoProducto==null) {
                JOptionPane.showMessageDialog(null, "No se puedo ingresar el producto","ERROR",JOptionPane.ERROR_MESSAGE);
            } else {
                String cantidadtxt = JOptionPane.showInputDialog(null, "Ingrese la cantidad de unidades que hay del producto");
                int cantidad = Integer.parseInt(cantidadtxt);
            
                if (cantidad>0) {
                    Establecimiento establecimiento = empleadoBodega.getEstablecimiento();
                    Existencia existencia = new Existencia(nuevoProducto,establecimiento,cantidad);

                    nuevoProducto.ejecutarInstruccionPSQL(Producto.INSERT);
                    existencia.ejecutarInstruccionPSQL(Existencia.INSERT);
                    this.actualizarTabla();
                } else {
                    JOptionPane.showMessageDialog(null, "El valor ingresado no es correcto");
                }
            }
            
        }
        
    }//GEN-LAST:event_jButtonIngresarNuevoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarProducto;
    private javax.swing.JButton jButtonIngresarNuevo;
    private javax.swing.JButton jButtonVerProductos;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldRol;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
